import './globals.css'
import { Providers } from './Providers'
import Navbar from './Navbar'

export const metadata = {
  title: 'Biggan PathShala ',
  description: 'Generated by Rownok',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className="">
        <main>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
